### PR TITLE
feat: Added EquatableAttribute.IgnoreBaseClassProperties parameter.

### PR DESCRIPTION
**Pull request by HavenDV**
Another option from https://github.com/Fody/Equals#configurability
Needed in some cases in Explicit mode to ignore comparison of base classes.

### CODE REVIEW

**Comment by diegofrata** [comment]
Happy to have this included, but could you add test cases for this feature?

**Comment by HavenDV** [comment]
Just to clarify, would you accept a PR that formats the generated code so it's readable?

**Comment by HavenDV** [comment]
> Yeah, I would definitely accept a PR for that if it doesn't make the code-generation any more unreadable than it already is.

I gave an example in my post, does this formatting suit you?

**Comment by diegofrata** [comment]
I am happy with the formatting in your example. Happy for you to submit it in a different PR!

One small thing so that I can merge this PR: can you change `IgnoreBaseClassProperties` to `IgnoreInheritedMembers`? Not sure if you had seen my earlier comment on it, but we support both records and classes, and might also support fields in addition to properties in the future.

**Comment by HavenDV** [comment]
I also see a small problem with tests and in general with the operation of the generator in VS due to Debugger.Break. I will also provide a PR for this
image

**Pull request merged**
