### PR TITLE
Breaking API change to support base type comparison. 

### PR DESCRIPTION
**Pull request by diegofrata**
Equals made protected and IEquatable<T> made explicit for classes. This should sort out the last issue with comparing derived types cast as base-type.

Solves #43

### CODE REVIEW

**Comment by diegofrata** [comment]
@christianrondeau are you happy with this fix?

**Comment by christianrondeau** [comment]
I'm looking at the branch, is that the eventual 3.0? And FYI I got this when referencing directly from source, it's annoying when you don't have VS installed :D

image

You could check for an environment variable, or a precompiler directive other than DEBUG.

So, I had this that you may find interesting:

image

**Comment by diegofrata** [comment]
@christianrondeau I have fixed the private/protected modifier and added extra tests. On the `<generated/>` comment I could not find any guidelines or docs for use -- I am not entirely sure this does anything that's not already accomplished by the `GeneratedCodeAttribute`.

If you have any pointers to it, let me know.

**Comment by diegofrata** [comment]
These changes are available on 3.0.0-beta001 if you want to give that a go!

**Comment by christianrondeau** [comment]
You may be right, anyway I also got it wrong, it's actually `<auto-generated />`
 https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview does it but doesn't explain why... I guess it's just to make it clear. But I guess it doesn't really matters.

I'll pull and try it when I have some time :)

**Pull request merged**
